### ISSUE TITLE
Link to OWASP Top 10 is Dead

### ISSUE THREAD

**Issue by sjlehn** [defuse/crackstation#6]
The OWASP Top Ten Vulnerability list on https://crackstation.net/hashing-security.htm has moved to https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf

**Comment by KrzysztofSakowski** [comment]
Created pull request: https://github.com/defuse/crackstation/pull/7

**Comment by KrzysztofSakowski** [comment]
@sjlehn resolved in https://github.com/defuse/crackstation/pull/7 Can be closed.
